name: White Haute Photography
favicon: null
layout_spectrum: 0.17452
typography_spectrum: 0.7376
title: White Haute Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252525'
    - '#80857e'
    - '#fafafa'
    - '#9fc4bd'
    - '#7a8780'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
